### ISSUE TITLE
How do I run these codes

### ISSUE THREAD

**Issue by Zumbalamambo** [abdelrahman-gaber/Faster-RCNN-Evaluation#1]
Please add wiki

**Comment by a64bit** [comment]
Hi Zumbalamambo, 

This repo contains my work to evaluate Faster-RCNN for pedestrian detection on different pedestrian datasets. It is ongoing work and not complete yet, which means there are still some issues with the evaluation criteria and some possible bugs in the codes. 

The codes here use the ground truth of each dataset stored in text files named with the name of corresponding images, and detection results from faster-rcnn stored in csv files (original caffe faster-rcnn code); then apply the evaluation criteria in these papers: 
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.402.6884&rep=rep1&type=pdf
https://arxiv.org/pdf/1607.07032.pdf

To run these codes you need to give the python codes the required arguments, with the full path to annotations, detection results, and output files to store the results. Try: python "file-name.py" --help to know what arguments the code needs. As I mentioned before, this work is not complete yet, so, when we make sure that everything is ok, I will add the wiki and some instructions to run it. 

Thank you.
